# dove Homebrew formula — GENERATED by dove's scripts/render-tap-files.sh.
# Do not hand-edit; regenerate for a new release rather than patching checksums.
#
#   brew install boomctl/tap/dove
class Dove < Formula
  desc "Send a file out of your own cloud — encrypted, expiring, one command"
  homepage "https://dove.sh"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/boomctl/dove/releases/download/v0.2.0/dove-aarch64-apple-darwin"
      sha256 "157813f0b49401ebf82f48f5deec3d79be2bd87422ddf4c1035beb9f231e7ac6"
    end
    on_intel do
      url "https://github.com/boomctl/dove/releases/download/v0.2.0/dove-x86_64-apple-darwin"
      sha256 "ad99bf4713bd181f433c3fdc5534585c7ce9cc8380056c0d759c7ad106987c7a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/boomctl/dove/releases/download/v0.2.0/dove-aarch64-unknown-linux-musl"
      sha256 "25538c15cb290b4cc0b3793ffcbfeed01ccebc53afa9ed7641a8829477a5a2c5"
    end
    on_intel do
      url "https://github.com/boomctl/dove/releases/download/v0.2.0/dove-x86_64-unknown-linux-musl"
      sha256 "a9857b30c979bdbe1e128e92149b21176672c64dc99ab6794fd97d2b7e98065f"
    end
  end

  def install
    bin.install Dir["dove-*"].first => "dove"
  end

  test do
    assert_match "dove #{version}", shell_output("#{bin}/dove --version")
  end
end
