# dove Homebrew formula — GENERATED by dove's scripts/render-tap-files.sh.
# Do not hand-edit; regenerate for a new release rather than patching checksums.
#
#   brew install boomctl/tap/dove
class Dove < Formula
  desc "Send a file out of your own cloud — encrypted, expiring, one command"
  homepage "https://dove.sh"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/boomctl/dove/releases/download/v0.1.0/dove-aarch64-apple-darwin"
      sha256 "6a0650031adbcfb17ab506e93d28d00b7466e0019165bc19f42d3f802e86146f"
    end
    on_intel do
      url "https://github.com/boomctl/dove/releases/download/v0.1.0/dove-x86_64-apple-darwin"
      sha256 "7b9473de03fdc46b56153593e6ae0af020cc2b63b7f31ba281de1766d3ef8c6a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/boomctl/dove/releases/download/v0.1.0/dove-aarch64-unknown-linux-musl"
      sha256 "f3ec4d88a93c2cb2984de6c0dd171e4d4c5b02c139ba55880e36cfc9637169ec"
    end
    on_intel do
      url "https://github.com/boomctl/dove/releases/download/v0.1.0/dove-x86_64-unknown-linux-musl"
      sha256 "bdf1de8ed6bd82c473d4522475ec16a0d2b92dca06a33550ff05bbe11bb9304e"
    end
  end

  def install
    bin.install Dir["dove-*"].first => "dove"
  end

  test do
    assert_match "dove #{version}", shell_output("#{bin}/dove --version")
  end
end
