# git-ark Homebrew formula — GENERATED by git-ark's scripts/render-tap-files.sh.
# Do not hand-edit; regenerate for a new release rather than patching checksums.
#
#   brew tap boomctl/tap
#   brew install git-ark
class GitArk < Formula
  desc "Write-only backup vault that fronts your own git host"
  homepage "https://github.com/boomctl/git-ark"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/boomctl/git-ark/releases/download/v0.6.0/git-ark-aarch64-apple-darwin"
      sha256 "f43691d477229493986b03af8a58a1a1746c73a8090b6ed7841a07cda5ebe913"
    end
    on_intel do
      url "https://github.com/boomctl/git-ark/releases/download/v0.6.0/git-ark-x86_64-apple-darwin"
      sha256 "538d026a642fdfd6cf4d46898f6240d12e0b5ef28f58361ebdfd914d813918ff"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/boomctl/git-ark/releases/download/v0.6.0/git-ark-aarch64-unknown-linux-musl"
      sha256 "ed4409167d6c5fde1893ec9a06d834666fe4f7d313a2b20dbdd3f87303d0a9e5"
    end
    on_intel do
      url "https://github.com/boomctl/git-ark/releases/download/v0.6.0/git-ark-x86_64-unknown-linux-musl"
      sha256 "6abfd7575d6ad6abfe400c111f34fdb20ac636e4388c243dbadf684fa5469051"
    end
  end

  def install
    bin.install Dir["git-ark-*"].first => "git-ark"
  end

  test do
    assert_match "git-ark #{version}", shell_output("#{bin}/git-ark --version")
  end
end
