# git-ark Homebrew formula — GENERATED by git-ark's scripts/render-tap-files.sh.
# Do not hand-edit; regenerate for a new release rather than patching checksums.
#
#   brew tap boomctl/tap
#   brew install git-ark
class GitArk < Formula
  desc "Write-only backup vault that fronts your own git host"
  homepage "https://github.com/boomctl/git-ark"
  version "0.3.2"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/boomctl/git-ark/releases/download/v0.3.2/git-ark-aarch64-apple-darwin"
      sha256 "83bfdb9a8e8bcc06be99f3708ed4c72dd85884622dcfbb297299273a056d4e42"
    end
    on_intel do
      url "https://github.com/boomctl/git-ark/releases/download/v0.3.2/git-ark-x86_64-apple-darwin"
      sha256 "871861a15a80438b8c757182423f70303ed6d3702940e5c1af5c68331f2563e7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/boomctl/git-ark/releases/download/v0.3.2/git-ark-aarch64-unknown-linux-musl"
      sha256 "d6d51c47be03ed9176c4a9d89ac6e8b0d33b50680f73b005b70c16daf3c0be1c"
    end
    on_intel do
      url "https://github.com/boomctl/git-ark/releases/download/v0.3.2/git-ark-x86_64-unknown-linux-musl"
      sha256 "27efe285c93fd44ce3e406ef8a0651a9d1e37de77ee85c60af24ec1be7f61528"
    end
  end

  def install
    bin.install Dir["git-ark-*"].first => "git-ark"
  end

  test do
    assert_match "git-ark #{version}", shell_output("#{bin}/git-ark --version")
  end
end
