# git-ark Homebrew formula — GENERATED by git-ark's scripts/render-tap-files.sh.
# Do not hand-edit; regenerate for a new release rather than patching checksums.
#
#   brew tap boomctl/tap
#   brew install git-ark
class GitArk < Formula
  desc "Write-only backup vault that fronts your own git host"
  homepage "https://github.com/boomctl/git-ark"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/boomctl/git-ark/releases/download/v0.4.0/git-ark-aarch64-apple-darwin"
      sha256 "90abcbc3a8aa2fa258a49d1315e2834624604b672de3852282641baeaf99fd70"
    end
    on_intel do
      url "https://github.com/boomctl/git-ark/releases/download/v0.4.0/git-ark-x86_64-apple-darwin"
      sha256 "ea8cd3e3f21f5c65653e4660026ed169472175e90bd1943502a8684b78ac2857"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/boomctl/git-ark/releases/download/v0.4.0/git-ark-aarch64-unknown-linux-musl"
      sha256 "436ba073bc8e1ffae78eaf512bff92cc221fa3431decedcc61d732dfb9e70af2"
    end
    on_intel do
      url "https://github.com/boomctl/git-ark/releases/download/v0.4.0/git-ark-x86_64-unknown-linux-musl"
      sha256 "3f7bc8207239306a4674dede6e0e832f8a97f77758495156adc94e95a22b4ec7"
    end
  end

  def install
    bin.install Dir["git-ark-*"].first => "git-ark"
  end

  test do
    assert_match "git-ark #{version}", shell_output("#{bin}/git-ark --version")
  end
end
